### ISSUE TITLE
Add german translation

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/contao-workflow#12]
Provide german translation or at least activate transifex.

**Comment by kikmedia** [comment]
You may add me to Transifex repository if a helping hand is still needed.

**Comment by dmolineus** [comment]
@kikmedia I sent you an invitation. :-)

For anyone else, translations are managed on transifex now. Feel free to join the team at: https://www.transifex.com/netzmacht/contao-workflow/

**Comment by kikmedia** [comment]
Fine.

I will have a look after it within the next days. Do we agree that the term „workflow“ shouldn’t be translated since it is mentioned in the Duden dictionary (see https://www.duden.de/rechtschreibung/Workflow <https://www.duden.de/rechtschreibung/Workflow>).

**Comment by dmolineus** [comment]
Yes, please do not translate "workflow". I also didn't translate "transition" in the [german docs](https://netzmacht.github.io/contao-workflow/administration/begriffe.html), but that's up to you to translate it.

**Comment by kikmedia** [comment]
All right, that was some work to do. Could you please review the german translation?

**Comment by dmolineus** [comment]
Thanks @kikmedia and @bezin for your contribution. German translation is shipped with release 1.3.0.
