### ISSUE TITLE
Type error: Argument 2 passed to Netzmacht\Workflow\Flow\Security\Permission::guardValidPermission()

### ISSUE THREAD

**Issue by basistom** [netzmacht/contao-workflow#13]
Auftreten:
Wenn in einem Step ein limitPermission gesetzt ist kommt folgender Fehler beim Aufruf der Workflow-Übersicht im BE.

Type error: Argument 2 passed to Netzmacht\Workflow\Flow\Security\Permission::guardValidPermission() must be of the type string, null given, called in /var/www/vm-spreefels/htdocs/www.weiterfahren.com/htdocs/vendor/netzmacht/workflow/src/Flow/Security/Permission.php on line 100

**Comment by dmolineus** [comment]
Behoben mit ec753b3c4b4abd273aa066d9d51db78cb2d3a3bc. 

Problematisch ist, dass Contao den Datensatz speichert, obwohl keine Permission ausgewählt wurde.
