### ISSUE TITLE
Add backend icon

### ISSUE THREAD

**Issue by bezin** [netzmacht/contao-workflow#23]
Hello, 

we designed a little icon to use in the back-end menu. It is not finally there yet as it is a little blurry, but if you like it in general, I would prepare a PR for some future relase. 

![210209_154517](https://user-images.githubusercontent.com/4400435/107380361-17dc3400-6aee-11eb-84f5-4764d04c241a.png) 

![icon-workflow](https://user-images.githubusercontent.com/4400435/107382264-fda35580-6aef-11eb-9e8c-87b5d6616820.png)

Cheers

**Comment by bezin** [comment]
As requested I tried another icon and adapted the icon currently in use on the entities with a workflow configuration: 
![210210_184442](https://user-images.githubusercontent.com/4400435/107549490-2c90f880-6bd0-11eb-992c-4bbc5d13042a.png)

**Comment by dmolineus** [comment]
I really like the last one. I would appreciate if you contribute it to the extension.

**Comment by bezin** [comment]
See #24
