### ISSUE TITLE
Installations-Bugs

### ISSUE THREAD

**Issue by srhinow** [netzmacht/contao-workflow#6]
Die Installation unter Contao4.4 und PHP7.2 schlägt fehl. Da beim contao::warmup in drei Dateien der Namespace falsch ist:

>  Attempted to load class "MetaPalettes" from the global namespace.            
>  Did you forget a "use" statement for "ContaoCommunityAlliance\MetaPalettes\  
>  MetaPalettes"?  
> 

die drei Dateien sind:
vendor/netzmacht/contao-workflow/src/Resources/contao/dca/tl_member_group.php
vendor/netzmacht/contao-workflow/src/Resources/contao/dca/tl_user.php
vendor/netzmacht/contao-workflow/src/Resources/contao/dca/tl_user_group.php

dort müssen alle Vorkommen von 
`\MetaPalettes `
mit 
`\ContaoCommunityAlliance\MetaPalettes\MetaPalettes` 
ersetzt werden -> dann läuft es durch.

**Comment by dmolineus** [comment]
As a workaround you could install version `~1.11` of metapalettes

**Comment by dmolineus** [comment]
Fixed with 957edc2dfb9dde3d942cc734f6b6a8b7c8d2d0da.
