### ISSUE TITLE
Beispiel-Konfiguration DCA

### ISSUE THREAD

**Issue by basistom** [netzmacht/contao-workflow#7]
Ein Beispiel für die Integration in das Contao-BE wäre sehr hilfreich. Zum Beispiel: Wie kann ein Workflow für News-Artikel integriert werden, so dass in der BE-Detailspage eines  Newsartikels alle Status-Optionen als Buttons angezeigt werden? Muss der Workflow in der News-Artikel-DCA integriert werden?

**Comment by dmolineus** [comment]
Im Ordner example befindet sich nun eine Beispiel-Integration. Zudem existiert nun ein rudimentäres [Handbuch](https://netzmacht.github.io/contao-workflow/), das nun einige Zusammenhänge erklärt.
